http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  estudiantes:
    host: localhost
    paths: '/api/v1/estudiantes'
  materias:
    host: localhost
    paths: '/api/v1/materias'
serviceEndpoints:
  httpbin: 
    url: 'https://httpbin.org'
  estudiantesservice:
    url: 'http://192.168.99.100:5000'
  materiasservice:
    url: 'http://192.168.99.100:5000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  listarestudiantes:
    apiEndpoints:
      - estudiantes
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: estudiantesservice
              changeOrigin: true
  listarmaterias:
    apiEndpoints:
      - materias
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: materiasservice
              changeOrigin: true
